[package]
name = "wasm"
version = "1.4.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
js-sys = "0.3.61"
thiserror = "1.0.39"
wasm-bindgen = "0.2.84"
wasm-bindgen-futures = "0.4.34"
